[package]
name = "todor-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
actix-cors = "0.6"
serde = { version = "1.0", features = ["derive"] }
env_logger = "0.9"
diesel = { version = "2.0", features = ["sqlite"] }
dotenvy = "0.15"